#druid 连接池
spring:
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSourcer
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      initial-size: 5 #初始连接数
      min-idle: 2 #最小连接数
      max-active: 15 #最大连接数
      max-wait: 60000 #等待连接的最长时间
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM dual